version: '3'

services:
 go_server:
   build: ./
   container_name: go_user
   extra_hosts:
      - "www.52db.club:172.19.139.129"
   ports:
      - "81:80"
   volumes:
      - ../:/apps
      # 日志存放路径，需要同级目录创建本目录
      - ../log:/apps/log
   working_dir: /apps/go_user
   command: ./main

