version: '3'

services:
 go_server:
   build: ./
   container_name: go_user
   environment:
      SERVICE_NAME: go_user
      SERVICE_TAGS: go_user,http,80
   ports:
      - "80:80"
   volumes:
      - ../:/apps
      # 日志存放路径，需要同级目录创建本目录
      - ../log:/apps/log
   working_dir: /apps/go_user
   command: ./main


