version: '3'

services:
 go_server:
   build: ./
   container_name: go_user
   environment:
      SERVICE_NAME: go_user
      SERVICE_TAGS: go_user,http,80
   extra_hosts:
      - "www.52db.club:139.224.132.234"
   ports:
      - "81:80"
   volumes:
      - ../:/apps
      # 日志存放路径，需要同级目录创建本目录
      - ../log:/apps/log
   working_dir: /apps/go_user
   command: ./main

   go_server_2:
     build: ./
     container_name: go_user_2
     environment:
       SERVICE_NAME: go_user
       SERVICE_TAGS: go_user,http,80
     extra_hosts:
       - "www.52db.club:139.224.132.234"
     ports:
       - "82:80"
     volumes:
       - ../:/apps
       # 日志存放路径，需要同级目录创建本目录
       - ../log:/apps/log
     working_dir: /apps/go_user
     command: ./main

